replace countryname="Bahamas" if countryname=="Bahamas. The"
replace countryname="Bolivia (Plurinational State of)" if countryname=="Bolivia"
replace countryname="Democratic Republic of the Congo" if countryname=="Congo. Dem. Rep."
replace countryname="Congo" if countryname=="Congo. Rep."
replace countryname="Democratic People's Republic of Korea" if countryname=="Korea. Dem. Rep."
replace countryname="Egypt" if countryname=="Egypt. Arab Rep."
replace countryname="Gambia" if countryname=="Gambia. The"
replace countryname="China, Hong Kong Special Administrative Region" if countryname=="Hong Kong SAR. China"
replace countryname="Iran (Islamic Republic of)" if countryname=="Iran. Islamic Rep."
replace countryname="Kyrgyzstan" if countryname=="Kyrgyz Republic"
replace countryname="Lao People's Democratic Repblic" if countryname=="Lao PDR"
replace countryname="China, Macao Special Administrative Region" if countryname=="Macao SAR. China"
replace countryname="Micronesia (Federated States of)" if countryname=="Micronesia. Fed. Sts."
replace countryname="Republic of Korea" if countryname=="Korea. Rep."
replace countryname="Republic of Moldova" if countryname=="Moldova"
replace countryname="Slovakia" if countryname=="Slovak Republic"
replace countryname="Saint Lucia" if countryname=="St. Lucia"
replace countryname="Saint Vincent and the Grenadines" if countryname=="St. Vincent and the Grenadines"
replace countryname="Taiwan" if countryname==""
replace countryname="United Republic of Tanzania" if countryname=="Tanzania"
replace countryname="United States of America" if countryname=="United States"
replace countryname="Venezuela (Bolivarian Republic of)" if countryname=="Venezuela. RB"
replace countryname="Viet Nam" if countryname=="Vietnam"
replace countryname="West Ban and Gaza Strip" if countryname=="West Bank and Gaza"
replace countryname="Yemen" if countryname=="Yemen. Rep."

